#FROM gcr.io/kubeflow-images-public/admission-webhook:v1.0.0-gaf96e4e3
FROM gcr.io/kubeflow-images-public/admission-webhook:v20190520-v0-139-gcee39dbc-dirty-0d8f4c
MAINTAINER zz<zhongzheng0813@163.com>
